### PR TITLE
Add missing LICENSE file, apache2

### PR DESCRIPTION
**Pull request by Blast545**
Add missing LICENSE file as part of the efforts to get this package to quality level 1

Signed-off-by: Jorge J. Perez <jjperez@ekumenlabs.com>

### CODE REVIEW

**Comment by Blast545** [comment]
Not an expert either, but this is addressed in other vendored libraries among ROS2 in the same way, for example: [console_bridge_vendor](https://github.com/ros2/console_bridge_vendor) and [spdlog_vendor](https://github.com/ros2/spdlog_vendor) (this one being MIT too)

The current solution in those packages is including the Apache2 license in the repository, and mention the vendor library code in the package.xml license

**Comment by Blast545** [comment]
@chapulina @dirk-thomas Can you give me your thoughts on this? Don't want to cause issues similar to this one: [tinydir_vendor license issue](https://github.com/ros2/tinydir_vendor/issues/7)

**Comment by dirk-thomas** [comment]
The license in this repo describes the license of the code in this repo. As such it is Apache 2. Adding an extra line in the manifest mentioning the license of the vendored library is what we have done in other packages and we should do the same here.

**Comment by Blast545** [comment]
@dirk-thomas So, there are no problems with this PR? The package manifest already included the reference to the MIT license of libyaml as you describe it should be.

**Pull request merged**
