### PR TITLE
[Backport Foxy] Included benchmark tests (#20)

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by ahcorde** [comment]
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12911/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7865/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10628/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12860/)

**Review by chapulina — APPROVED** [review]
I think #23 needs backporting too

**Review by chapulina — COMMENTED** [review]
Should this target the `foxy` branch?

**Comment by ahcorde** [comment]
I created another PR for the QD

**Pull request merged**
