### PR TITLE
Foxy backport: Fix target_link_directories/link_directories in cmake (#29)

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: ahcorde <ahcorde@gmail.com>

Otherwise, Foxy fails to build on Ubuntu 18.04.

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
Do you mind to sign the commit ?

**Comment by clalancette** [comment]
> Do you mind to sign the commit ?

Oops, yeah, good point.  Will do.

**Comment by clalancette** [comment]
There we go, DCO bot is happier now.

**Review by ahcorde — APPROVED** [review]

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13657/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8536/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/11372/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13721/)

**Comment by clalancette** [comment]
@jacobperron Both Linux CIs have failing tests in sros2, macOS has a small set of failures, and Windows has an even larger set of failures.  It seems pretty unlikely to me that any of these test failures were caused by this PR, but could you take a quick look?  Thanks.

**Comment by jacobperron** [comment]
The last time I recall running a full CI for Foxy was in December: https://github.com/ros2/ros2/pull/1070
I've seen the sros2 and laser_geometry test failures before, but the ros2doctor failure on macOS and the others on Windows look new to me. I agree that it seems unlikely that this PR would cause those to start failing. It's possible something else changed that is causing those to fail. Maybe it's a good time to trigger a full Foxy build to see what the where our baseline is now.

**Comment by jacobperron** [comment]
> Maybe it's a good time to trigger a full Foxy build to see where our baseline is now.

Here we go: https://github.com/ros2/ros2/issues/1090

**Comment by clalancette** [comment]
> Here we go: [ros2/ros2#1090](https://github.com/ros2/ros2/issues/1090)

Thanks, appreciated.  I'll make a decision on whether to merge this PR once those results come back.

**Comment by clalancette** [comment]
Hm.  Well, while there is a bunch of overlap between the CI job here and the one that Jacob pointed to, it's not 100%.  There are some failures here that are not in the unmodified job.  I still think it is unlikely that this change is the cause of those failures, but I'll hold off on merging this for now.

**Comment by clalancette** [comment]
I'm going to go ahead and merge this regardless of the warnings.  I highly doubt it is because of this PR.

**Pull request merged**
