### PR TITLE
Fix target_link_directories/link_directories in cmake

### PR DESCRIPTION
**Pull request by ahcorde**
Related with this issue https://github.com/ros2/libyaml_vendor/issues/28#event-4109220003

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Review by clalancette — APPROVED** [review]
Looks good to me with green CI.  Thanks for the patch @ahcorde !

**Comment by ahcorde** [comment]
Compiling up-to libyaml_vendor and testing libyaml_vendor

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/13264/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/8194/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10979/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/13293/)

**Comment by sloretz** [comment]
Foxy backport requested https://github.com/ros2/libyaml_vendor/issues/28#issuecomment-757358050

**Comment by jacobperron** [comment]
For the record, this was backported to Foxy in https://github.com/ros2/libyaml_vendor/pull/32.

**Pull request merged**
